name: gpl-covid
channels:
    - conda-forge
    - r
    - defaults
    - bolliger32
dependencies:
    - python=3.7
    - beautifulsoup4=4.9
    - black=19.10
    - blas=2.8=netlib
    - census=0.8
    - fuzzywuzzy=0.17
    - geopandas=0.7
    - jupyter=1.0
    - jupyterlab=2.1
    - lxml=4.4
    - netcdf4=1.5
    - nodejs=12.4
    - openpyxl=3.0
    - papermill=2.1
    - pip=20.0
    - pytest=5.4
    - requests=2.23
    - seaborn=0.10
    - xarray=0.15
    - xlrd=1.2
    - r-base=3.5
#     - rstudio=1.1
    - r-cowplot=1.0
    - r-data.table=1.12
    - r-downloader=0.4
    - r-ggsci=2.9
    - r-gridExtra=2.3
    - r-irkernel=1.1
    - r-lfe=2.8
    - r-lubridate=1.7
    - r-mvtnorm=1.1
    - r-padr=0.5
    - r-patchwork=1.0
    - r-rgdal=1.4
    - r-rgeos=0.5
    - r-rvest=0.3
    - r-tidyverse=1.3
    - r-tigris=0.9
    - pip:
        - ipystata==0.3
        - stata_kernel==1.11